destination: _site/
url: "http://127.0.0.1:4000"
baseurl: "/cxs-pdf"
port: 4000
output: pdf
product: cxs
print_title: Doc Pilot
print_subtitle: Summer 2018
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: cxs
